# Generated by Django 5.0.4 on 2024-05-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
